<?php
return [
    'admin_email' => 'kurineva85@mail.ru',
    'shop_name' => 'Магазин shop.loc',
    'smtp_login' => '',
    'smtp_password' => '',
    'pagination' => 3,
    'img_width' => 125,
    'img_height' => 200,
    'gallery_width' => 700,
    'gallery_height' => 1000,
    'news_img_width' => 795,
    'news_img_height' => 323,
    'slide_img_width' => 1600,
    'slide_img_height' => 650,
//    'smtp_host' => 'smtp.ukr.net',
//    'smtp_port' => '2525',
//    'smtp_protocol' => 'ssl',
//    'smtp_login' => 'testishop2@ukr.net',
//    'smtp_password' => 'testishop_2',
    'smtp_host' => 'smtp.rambler.ru',
    'smtp_port' => '465',
    'smtp_protocol' => 'ssl',
    'smtp_login' => 'vova.mezencev@rambler.ru',
    'smtp_password' => '1qaz2wsx3EDC',
];

